package lab16;

public enum DrinkTypeEnum {
    BEER, WINE, VODKA, BRANDY, CHAMPAGNE, WHISKEY, TEQUILA, RUM, VERMOUTH, LIQUOR, JAGERMEISTER,
    JUICE, COFFEE, GREEN_TEA, BLACK_TEA, MILK, WATER, SODA
}